eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 7884
spring:
  application:
    name: service-feign

ribbon:
  ServerListRefreshInterval: 5000
  okhttp:
    enabled: true
feign:
  okhttp:
    enabled: true