eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:8761/eureka/
  instance:
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    ip-address: 192.168.10.111
    prefer-ip-address: true

server:
  port: 7884
spring:
  application:
    name: service-feign