eureka:
  client:
    serviceUrl:
      defaultZone: http://server1:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: zuul
zuul:
  routes:

    api-a:
      path: /api-a/**     #api-a开头的发到service-ribbon
      serviceId: service-ribbon
    api-b:
      path: /api-b/**      #api-b开头的发到server-feign   /*只作用于下一层
      serviceId: service-feign