eureka:
  client:
    service-url:
      defaultZone: http://server1:8761/eureka  #注册到一个注册中心，另一个会自动同步，这样的坏处是一个挂了，整个注册中心的集群都失效了，所以最好还是指定每一个
  instance:
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    ip-address: 192.168.10.111
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 20 #eureka服务端接收到实例的最后一次心跳后，要等多久才剔除
    lease-renewal-interval-in-seconds: 10 #多久发一次心跳给服务器，表明它存活

server:
  port: 7882
spring:
  application:
    name: service-hi
